### ISSUE TITLE
Proposal to scale vectors with multiply and divide

### ISSUE THREAD

**Issue by cansik** [arisona/ether-gl#1]
What is the reason why there is a `subtract` and an `add` function for vectors (`Vec2`, `Vec3`, `Vec4`) but no `multiply` and `divide`?

At the moment if you want to divide a vector you have to `scale` it like this:

```java
Vec3 v = new Vec3(10f, 1f, 2f);
float divisor = 2f;

//divide vector
Vec3 dividedVec = v.scale(1/divisor);
```

### Problem
This does not look very intuitive when reading through code. It would be easier to read a `divide` or `multiply`.

And there is a bug that could easily happen if your divisor is an `integer` by mistake. The result will always be `0` and so the result vector would be a `Vec3.ZERO`.

```java
Vec3[] myVecs = new Vec3[20];
... //fill vectors

Vec3 sum = new Vec3(0f, 0f, 0f);

for(Vec3 v : myVecs)
    sum = sum.add(v);

//divide by number of vectors in list
Vec3 result = v.scale(1/myVecs.Length);
```

I know this is truly a developer failure but the framework could help developers if it would provide a function for **multiplying** and **dividing** vectors by a `scalar`.

### Implementation
Here is an example implementation for Vec2.

**Multiply**
Multiply is just implemented to fulfil the terminology of vector operations. It does the same thing as scale.

```java
public Vec2 multiply(float s) {
	return scale(s);
}
```

**Divide**
Divide just makes sure that the vector is multiplied by a float number.

```java
public Vec2 divide(float s) {
	return scale(1f/s);
}
```

What do you think about this? Or am I missing something?

**Comment by arisona** [comment]
The reason is that we try to stick to math terminology as far a possible: Vector arithmetics defines vector addition and subtraction (u + v, u - v) but not multiplication / division (u * v, u / v), except for special products such as dot or cross product. The scale method explicitly refers to scaling a vector with a scalar (s * u).
