### ISSUE TITLE
Linux+Mesa+Intel: OpenGL Shared Contexts not working

### ISSUE THREAD

**Issue by Morbrolhc** [arisona/ether-gl#2]
Since commit 33b112a the library does not work on linux with Mesa Intel Graphics.
Reported on Kubuntu 15.10 and Arch.

**Comment by arisona** [comment]
Most likely related to OpenGL shared contexts. Are there any additional infos / messages you get when the app crashes? (I assume it does crash, correct?)

**Comment by Chillons** [comment]
There is no additionial error message, the window opens for a split second and closes immediately.

Full output for CustomGeometryExample.java (applies to most examples): 

> scheduler: scene thread overload (max=16ms used=7ms)
scheduler: scene thread overload (max=16ms used=129ms)
scheduler: scene thread overload (max=16ms used=1204ms)
intel_do_flush_locked failed: No such file or directory

> Process finished with exit code 1

The number of scheduler entries varies from one to three.

**Comment by arisona** [comment]
could you try setting the environment variable LIBGL_DISABLE_DRI3=1 and then launch?

**Comment by arisona** [comment]
if this doesn't work, pull the latest commit and run with -Dgl_no_threads, which is more conservative in terms OpenGL context use, and would hopefully work with your configuration. otherwise let's debug on Thursday :-)

**Comment by Morbrolhc** [comment]
Both methods don't seem to work.
However, setting the enviroment variable LIBGL_ALWAYS_SOFTWARE=1 as proposed here https://jogamp.org/bugzilla/show_bug.cgi?id=873 does work. But I don't think this terrible workaround should be the solution.

**Comment by arisona** [comment]
My bad - there was a bug in the fix... I pushed an update. Maybe it works now... Software rendering indeed isn't an option.

**Comment by Morbrolhc** [comment]
It seems to work with the -Dgl_no_threads vm option. The examples and our project run. Thank you.

**Comment by arisona** [comment]
Ok, thank you - good that it works at least for now. Not sure how to deal with this in the long run, we need to use shared contexts at some point, but there seems to be a serious issue with intel/mesa drivers: http://jogamp.org/deployment/v2.3.2/javadoc/jogl/javadoc/

**Comment by arisona** [comment]
I'm leaving this issue open for now: Apparently, shared OpenGL contexts do not work properly on Linux with Mesa+Intel+JOGL. This issue has been around for a couple of years and doesn't seem to be fixed. Until resolved, there seems no solution but to declare Linux+Intel as unsupported (as others do). :-(
